[versions]
agp = "8.1.3"
buildconfig = "4.1.2"
compose = "1.5.3"
kotlin = "1.9.10"
kotlinx-abi-plugin = "0.13.2"
kotlinx-datetime = "0.5.0"
kotlininject = "0.6.3"
ksp = "1.9.10-1.0.13"
kstore = "0.6.0"
ktor = "2.3.6"
maven-publish = "0.25.3"
moshi = "1.15.0"
serialization = "1.6.0"
workflow = "1.12.1-beta01"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.12.0" }
androidx-icons-extended = { module = "androidx.compose.material:material-icons-extended", version = "1.5.4" }
retainedactivity = { module = "dev.marcellogalhardo:retained-activity", version = "1.0.1" }

appdirs = { module = "ca.gosyer:kotlin-multiplatform-appdirs", version = "1.1.1" }
kamel = { module = "media.kamel:kamel-image", version = "0.8.2" }
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }
kstore-file = { module = "io.github.xxfast:kstore-file", version.ref = "kstore" }
kstore-storage = { module = "io.github.xxfast:kstore-storage", version.ref = "kstore" }
zoomable = { module = "me.saket.telephoto:zoomable", version = "0.6.2" }

apache-commons = { module = "org.apache.commons:commons-lang3", version = "3.13.0" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.9" }

kotlininject = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlininject" }
kotlininject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlininject" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.14.2" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okio = { module = "com.squareup.okio:okio", version = "3.6.0" }

kotlinx-abi = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-abi-plugin" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version = "0.22.0" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }

maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

workflow-core = { module = "com.squareup.workflow1:workflow-core", version.ref = "workflow" }
workflow-runtime = { module = "com.squareup.workflow1:workflow-runtime", version.ref = "workflow" }

bluesky = { module = "sh.christian.ozone:bluesky", version = "0.0.4" }
